// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"td-blog/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/articles",
				Handler: CreateArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/articles",
				Handler: ListArticlesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/articles/:id",
				Handler: GetArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/articles/:id/comments",
				Handler: AddCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/articles/:id/comments",
				Handler: ListCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/categories",
				Handler: ListCategoriesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/users/:id",
				Handler: GetUserProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/users/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/users/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)
}
